/*
 389. Find the Difference

 You are given two strings s and t.
 String t is generated by random shuffling string s and then add one more letter at a random position.
 Return the letter that was added to t.

 Example 1:

 Input: s = "abcd", t = "abcde"
 Output: "e"
 Explanation: 'e' is the letter that was added.

 Example 2:

 Input: s = "", t = "y"
 Output: "y"

 Constraints:

 0 <= s.length <= 1000
 t.length == s.length + 1
 s and t consist of lowercase English letters.
 */

class Solution {
    // Straight approach with time complexity O(N)
    func findTheDifference(_ s: String, _ t: String) -> Character {
        var dict: [Character: Int] = [:]
        for c in s {
            dict[c,default: 0] += 1
        }
        for c in t {
            guard let char = dict[c] else { return c }
            dict[c] = char - 1
            if char - 1 < 0 {
                return c
            }
        }
        return Character("")
    }
}

var sol = Solution()
sol.findTheDifference("bbca", "bbcaa")
